version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: nest_loja_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loja
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loja-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_loja_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    command:
      ['bash', '/wait-for-it.sh', 'postgres:5432', '--', 'node', 'dist/main.js']

    networks:
      - loja-network

volumes:
  postgres_data:

networks:
  loja-network:
    driver: bridge
